version: '3.9'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
    
  database:
    image: postgres:latest
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${TZ}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
